/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecuerdosRouteImport } from './routes/recuerdos'
import { Route as MensajeRouteImport } from './routes/mensaje'
import { Route as ContadorRouteImport } from './routes/contador'
import { Route as IndexRouteImport } from './routes/index'

const RecuerdosRoute = RecuerdosRouteImport.update({
  id: '/recuerdos',
  path: '/recuerdos',
  getParentRoute: () => rootRouteImport,
} as any)
const MensajeRoute = MensajeRouteImport.update({
  id: '/mensaje',
  path: '/mensaje',
  getParentRoute: () => rootRouteImport,
} as any)
const ContadorRoute = ContadorRouteImport.update({
  id: '/contador',
  path: '/contador',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contador': typeof ContadorRoute
  '/mensaje': typeof MensajeRoute
  '/recuerdos': typeof RecuerdosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contador': typeof ContadorRoute
  '/mensaje': typeof MensajeRoute
  '/recuerdos': typeof RecuerdosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contador': typeof ContadorRoute
  '/mensaje': typeof MensajeRoute
  '/recuerdos': typeof RecuerdosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contador' | '/mensaje' | '/recuerdos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contador' | '/mensaje' | '/recuerdos'
  id: '__root__' | '/' | '/contador' | '/mensaje' | '/recuerdos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContadorRoute: typeof ContadorRoute
  MensajeRoute: typeof MensajeRoute
  RecuerdosRoute: typeof RecuerdosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recuerdos': {
      id: '/recuerdos'
      path: '/recuerdos'
      fullPath: '/recuerdos'
      preLoaderRoute: typeof RecuerdosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensaje': {
      id: '/mensaje'
      path: '/mensaje'
      fullPath: '/mensaje'
      preLoaderRoute: typeof MensajeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contador': {
      id: '/contador'
      path: '/contador'
      fullPath: '/contador'
      preLoaderRoute: typeof ContadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContadorRoute: ContadorRoute,
  MensajeRoute: MensajeRoute,
  RecuerdosRoute: RecuerdosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
